version: '3.8'

services:
  db:
    image: postgres:13
    container_name: property_listings_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=property_listings
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    container_name: property_listings_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
